title: <p align="center"> Chris Tran </p>

logo: "/images/IMG_20210807_143527_112_2.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/supriyo_CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/supriyo-jana-0972a7147/">LinkedIn</a> |
  <a href="https://github.com/hungryrag">GitHub</a>
  </p>
  
  <p align="justify">
  I completed my B.Tech in Computer Science & Engineering from University of Engineering & Management, Kolkata.
  <br><br>
  I am currently a System Engineer at TATA Consultancy Services working with Spring.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
